apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freqtrade-helm.fullname" . }}-strategy
data:
  strategy.py: |
    {{ .Values.freqtrade.strategy | nindent 4 }}
  strategy.json: |
    {{ .Values.freqtrade.strategy_params | nindent 4 }}

