apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freqtrade-helm.fullname" . }}
  labels:
    {{- include "freqtrade-helm.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "freqtrade-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config_map_config.yaml") . | sha256sum }}
        checksum/strategy: {{ include (print $.Template.BasePath "/config_map_strategy.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "freqtrade-helm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "freqtrade-helm.serviceAccountName" . }}
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              pip install psycopg2-binary
              freqtrade trade --strategy {{ .Values.freqtrade.strategyName }} --config /freqtrade/user_data/config/config.json --db-url {{ .Values.freqtrade.dbUrl }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /freqtrade/user_data/config
            - name: strategy-volume
              mountPath: /freqtrade/user_data/strategies
            - name: db-volume
              mountPath: /freqtrade/user_data/db
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "freqtrade-helm.fullname" . }}-config
        - name: strategy-volume
          configMap:
            name: {{ include "freqtrade-helm.fullname" . }}-strategy
        - name: db-volume
          persistentVolumeClaim:
            claimName: {{ include "freqtrade-helm.fullname" . }}-db
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
