apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freqtrade-helm.fullname" . }}-db
  labels: {{- include "freqtrade-helm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
