apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freqtrade-user-data
  labels: { { - include "freqtrade-helm.labels" . | nindent 4 } }
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
