apiVersion: v1
entries:
  freqtrade-helm:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-14T01:20:58.514533+08:00"
    description: A Helm chart for Kubernetes
    digest: 8af969fb67b97b73f3dd3b5eef096f0439dd1b47546cf2e8e670744beb4c8445
    name: freqtrade-helm
    type: application
    urls:
    - freqtrade-helm-0.1.0.tgz
    version: 0.1.0
generated: "2025-04-14T01:20:58.513415+08:00"
