apiVersion: v1
entries:
  freqtrade-helm:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-14T08:57:37.71979+08:00"
    description: A Helm chart for Kubernetes
    digest: c8de68495f2b99c68b3c52d06c0d87af5526d56e874c9e3b937297331a5afb65
    name: freqtrade-helm
    type: application
    urls:
    - freqtrade-helm-0.1.0.tgz
    version: 0.1.0
generated: "2025-04-14T08:57:37.718602+08:00"
