apiVersion: v1
kind: ConfigMap
metadata:
  name: freqtrade-config
  namespace: freqtrade
data:
  config.json: |
    {
        "$schema": "https://schema.freqtrade.io/schema.json",
        "max_open_trades": 5,
        "stake_currency": "USDT",
        "stake_amount": 300,
        "tradable_balance_ratio": 0.9,
        "fiat_display_currency": "USD",
        "stoploss_on_exchange": true,
        "dry_run": true,
        "dry_run_wallet": 1667,
        "cancel_open_orders_on_exit": false,
        "trading_mode": "spot",
        "margin_mode": "",
        "unfilledtimeout": {
            "entry": 10,
            "exit": 30,
            "exit_timeout_count": 0,
            "unit": "minutes"
        },
        "order_types": {
            "entry": "limit",
            "exit": "limit",
            "emergency_exit": "market",
            "force_entry": "market",
            "force_exit": "market",
            "stoploss": "market",
            "stoploss_on_exchange": false,
            "stoploss_on_exchange_interval": 60
        },
        "entry_pricing": {
            "price_side": "same",
            "use_order_book": false,
            "order_book_top": 1,
            "price_last_balance": 0.0,
            "check_depth_of_market": {
                "enabled": false,
                "bids_to_ask_delta": 1
            }
        },
        "exit_pricing": {
            "price_side": "same",
            "use_order_book": true,
            "order_book_top": 1
        },
        "exchange": {
            "name": "bybit",
            "key": "",
            "secret": "",
            "ccxt_config": {},
            "ccxt_async_config": {},
            "pair_whitelist": [
                "WLD/USDT",
                "RSS3/USDT",
                "SUI/USDT",
                "GTAI/USDT",
                "GRT/USDT",
                "RENDER/USDT",
                "CGPT/USDT",
                "FLOCK/USDT",
                "ROSE/USDT",
                "ZIG/USDT",
                "AGI/USDT",
                "ARKM/USDT",
                "LMWR/USDT",
                "PRIME/USDT",
                "COOKIE/USDT",
                "ATH/USDT",
                "INJ/USDT",
                "AIOZ/USDT",
                "BOME/USDT",
                "PEOPLE/USDT",
                "TOKEN/USDT",
                "COQ/USDT",
                "LADYS/USDT",
                "BABYDOGE/USDT",
                "BRETT/USDT",
                "RVN/USDT",
                "BONK/USDT",
                "FLOKI/USDT",
                "DEGEN/USDT",
                "KSM/USDT",
                "PONKE/USDT",
                "VINU/USDT",
                "SHIB/USDT",
                "DOGE/USDT",
                "PEPE/USDT",
                "WIF/USDT",
                "MEME/USDT",
                "POPCAT/USDT",
                "MOG/USDT",
                "SUNDOG/USDT",
                "SC/USDT",
                "GOAT/USDT",
                "SPX/USDT",
                "MYRO/USDT",
                "DOGS/USDT",
                "HMSTR/USDT",
                "TRUMP/USDT",
                "PUFF/USDT",
                "CATS/USDT",
                "MOJO/USDT",
                "TOSHI/USDT",
                "XAUT/USDT",
                "FHE/USDT",
                "BABY1/USDT",
                "STOP/USDT",
                "LUCE/USDT",
                "HAT/USDT",
                "FET/USDT",
                "VIRTUAL/USDT",
                "AI16Z/USDT",
                "PUMP/USDT",
                "CORN/USDT",
                "KILO/USDT",
                "B3TR/USDT",
                "WAL/USDT",
                "AMI/USDT",
                "VVV/USDT",
                "BR/USDT"
            ],
            "pair_blacklist": [
                ".*3S\/USDT",
                ".*3L\/USDT",
                "TFUEL\/BTC",
                "ONE\/BTC",
                "ATOM\/BTC",
                "XMR\/BTC",
                "BNB\/BUSD",
                "BNB\/BTC",
                "BNB\/ETH",
                "BNB\/EUR",
                "BNB\/NGN",
                "BNB\/PAX",
                "BNB\/RUB",
                "BNB\/TRY",
                "BNB\/TUSD",
                "BNB\/USDC",
                "BNB\/USDS",
                "BNB\/USDT",
                "EUR\/USDT",
                ".*/BTC",
                ".*UP\/USDT",
                ".*DOWN\/USDT",
                ".*BEAR\/USDT",
                ".*BULL\/USDT",
                "WEN/USDT",
                "PEOPLE/USDT",
                "PARTI/USDT",
                "PUFF/USDT"
            ]
        },
        "pairlists": [
            {
                "method": "StaticPairList"
            }
        ],
        "telegram": {
            "enabled": false,
            "token": "",
            "chat_id": ""
        },
        "api_server": {
            "enabled": true,
            "listen_ip_address": "0.0.0.0",
            "listen_port": 8080,
            "verbosity": "error",
            "enable_openapi": false,
            "jwt_secret_key": "",
            "ws_token": "OtENfUEvjftTth_xOKTjHBNUOhkzqCE-dA",
            "CORS_origins": [
                "http://localhost:8082"
            ],
            "username": "",
            "password": ""
        },
        "bot_name": "freqtrade",
        "initial_state": "running",
        "force_entry_enable": false,
        "internals": {
            "process_throttle_secs": 5
        }
    }
